name: PR

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  checks:
    uses: palasthotel/github-workflows/.github/workflows/wp-plugin-pr.yml@v1
    with:
      slug: disable-attachment-pages
      dev-plugin-name: Disable Attachment Pages - DEV
